### ISSUE TITLE
Filtering does not work correctly

### ISSUE THREAD

**Issue by ReinierNL** [TNOCS/csWeb#141]
See the image below:
![image](https://cloud.githubusercontent.com/assets/11029099/8405356/277c077e-1e54-11e5-892d-27c8c68f4c83.png)

Note: the energy label value is in this case an integer, ranging from 0 to 8.
There are two things wrong here:
1. There is a building with value *6* that should not be shown (should not pass the filter)
2. The chart itself does not look right. The bars should appear *at* the integer values (tick marks on horizontal axis) in stead of somewhere near them.

**Comment by erikvullings** [comment]
I'm not sure whether your issue is fixed too, but I assume it is. I only have to fix some other issues before I can commit the fix. Just closing it so no one else will start working on it.

Details of my fix:
In BarFilterCtrl.initBarFilter, the group filter contained an error computing the bins. 
```Math.floor(a / binWidth) * binWidth;``` 
should have been
```min + Math.floor(a / binWidth) * binWidth;```
By neglecting the minimum, we would always loose the smallest features (expect when the minimum was 0).

In addition, the max needed to be increased too, otherwise we would loose the features with the largest property value.

This fix still needs to be applied to the ScatterFilter too.
