### ISSUE TITLE
Loading layer animation doesn't stop.

### ISSUE THREAD

**Issue by erikvullings** [TNOCS/csWeb#64]

**Comment by damylen** [comment]
could you be more specific, it seems to stop for the layers I'm working on

**Comment by erikvullings** [comment]
Not for the flight radar not hospital on my PC. But perhaps you're out of sync, and something went wrong in a merge, as I also had to fix the display of property values.

Sent from my Windows Phone

-----Original Message-----

**Comment by rinzeb** [comment]
This happened on my PC too, when loading a layer failed (e.g. when the geojson file could not be found). However, it was fixed in this commit https://github.com/TNOCS/csMap/commit/953ec18deb53888e812444583767069fb0163efd  For me the spinner disappears normally now, either after loading the layer or after a loading-error message is issued.
